/**
 * DEMO_MODE adapters.
 *
 * Replaces the three external dependencies — Supabase, the Flask ML service,
 * and Groq — with local implementations so the full application runs with no
 * credentials and no Python.
 *
 * WHAT IS REAL IN DEMO MODE
 *   · the query router and its gazetteer
 *   · the tri-state presence resolution and deterministic override
 *   · the ENTIRE status masking boundary, including the egress filter
 *   · the Context Fusion prompt construction
 *   · retrieval by exact cosine over embedded chunks
 *   · both pipeline arms and the single-branch mode flag
 *
 * WHAT IS FAKE IN DEMO MODE — and must never be reported
 *   · the classifier. It is a schedule lookup, NOT a Random Forest. There is
 *     no trained model, so there is nothing to serve (audit R6).
 *   · the language model. Answers are composed from templates over the
 *     retrieved context, NOT generated by Llama 3.1 8B (audit R5/R8).
 *   · the embeddings. Hashed lexical overlap, NOT all-MiniLM-L6-v2.
 *
 * Every response in demo mode carries `demoMode: true`, /api/health reports it,
 * the UI shows a persistent banner, and /api/eval/* refuses to run. The point
 * is that nobody — including a tired researcher at 2am — can mistake a demo
 * screenshot for a result.
 */

import * as D from './data.js';
import { demoDb } from './db.js';
import { embed } from './embeddings.js';

export { demoDb };

/**
 * Stand-in for the Flask service.
 *
 * /predict deliberately reports source: 'schedule_lookup'. It is NOT dressed up
 * as a model prediction: the probability vector is one-hot, which is what a
 * deterministic rule produces, and any UI or log reading it can tell the
 * difference.
 */
export const demoMl = {
  async embed(text) {
    return { embedding: embed(text), dim: 384, model: 'demo-lexical-hash (NOT all-MiniLM-L6-v2)' };
  },

  async predict(context) {
    const faculty = D.faculty.find(
      (f) => D.facultyPseudonymMap.find((m) => m.pseudonym_id === context.pseudonym_id)?.faculty_id === f.id,
    );
    const { data } = await demoDb.rpc('schedule_lookup_status', {
      p_faculty_id: faculty?.id,
      p_at: context.when,
    });
    const status = data[0].status_code;

    return {
      predicted_class: status,
      // One-hot, because a rule is not probabilistic. A real forest returns a
      // distribution; this deliberately does not pretend to.
      probabilities: Object.fromEntries(
        D.availabilityStatus.map((s) => [s.code, s.code === status ? 1 : 0]),
      ),
      model_version: 'DEMO-schedule-lookup',
      label_source: 'schedule_derived',
      source: 'schedule_lookup',
      internal_only: true,
    };
  },

  async modelInfo() {
    return {
      rf_ready: false,
      demo: true,
      message:
        'Demo mode: availability comes from a deterministic schedule lookup. ' +
        'No Random Forest has been trained.',
    };
  },

  async health() {
    return { status: 'ok', demo: true, embedder: 'demo-lexical-hash', rf_ready: false };
  },
};

/**
 * Stand-in for Groq.
 *
 * Composes an answer from the retrieved context using templates. It is
 * extractive by construction, which has one useful property: it CANNOT
 * hallucinate a room number, so the egress filter has nothing to catch in demo
 * mode. That is a property of the stub, not evidence the filter works — the
 * evidence for that is `npm test`.
 */
export async function demoGenerate(messages) {
  const prompt = messages.at(-1)?.content ?? '';

  const query = (prompt.match(/USER QUERY:\n([\s\S]*)$/) ?? [])[1]?.trim() ?? '';
  const availability = (prompt.match(/AVAILABILITY \([^)]*\):\n([\s\S]*?)\n\n/) ?? [])[1] ?? null;
  const contextBlock = (prompt.match(/RETRIEVED CONTEXT[^:]*:\n([\s\S]*?)(?:\n\nAVAILABILITY|\n\nUSER QUERY)/) ?? [])[1] ?? '';

  const passages = contextBlock
    .split(/\n\n---\n\n/)
    .map((b) => b.replace(/^\[\d+\][^\n]*\n/, '').trim())
    // The prompt's own "(no relevant institutional documents were retrieved)"
    // placeholder is not a passage. Without this it gets spliced into the
    // answer as though it were retrieved text.
    .filter((b) => b && !b.startsWith('(no relevant'));

  // Simulated inference latency, so the typing indicator is visible and the
  // demo feels like the real thing.
  await new Promise((r) => setTimeout(r, 280 + Math.random() * 320));

  const noContext = passages.length === 0;

  if (availability) {
    const name = (availability.match(/Faculty member: (.+)/) ?? [])[1] ?? 'The faculty member';
    const status = (availability.match(/Estimated status: (.+)/) ?? [])[1] ?? 'Unavailable';
    // Deliberately does NOT splice in the top retrieved chunk. The lexical
    // embedder ranks weakly on availability phrasing, so the best chunk is
    // often unrelated, and tacking it on would make the answer look like the
    // real pipeline hallucinating rather than the stub being a stub.
    return (
      `Based on the current schedule, ${name} is estimated to be: ${status}. ` +
      'This is a schedule-derived estimate rather than a confirmed observation, ' +
      'so it is worth coordinating with the department office before visiting.'
    );
  }

  if (noContext) {
    return (
      'I do not have information about that in the documents available to me. ' +
      'Try asking about a campus building, an administrative office, or an ' +
      'institutional policy covered by the university documents.'
    );
  }

  return `${firstSentences(passages[0], 3)}${
    passages[1] ? ` ${firstSentences(passages[1], 1)}` : ''
  }${
    /where|location|find|nasaan|saan/i.test(query)
      ? ' You can see the exact position highlighted on the campus map.'
      : ''
  }`;
}

function firstSentences(text, n) {
  return text.split(/(?<=[.!?])\s+/).slice(0, n).join(' ').trim();
}
