import { useEffect, useState } from 'react';
import { ChevronDown, FlaskConical } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { api } from '../../frontend-utilities/backendApiClient.js';

/**
 * Demonstration-mode notice.
 *
 * A slim ruled bar rather than a filled slab: persistent, high contrast, and
 * concise, with the detail behind an accessible disclosure rather than three
 * lines of small print on every screen.
 *
 * It is NOT dismissible, and that is deliberate. This is a research-integrity
 * control, not a marketing toast. The failure it guards against is mundane
 * and real: a screenshot taken during a demo ending up in a slide deck or a
 * thesis draft, where a schedule lookup reads as a trained classifier and
 * templated text reads as a language model.
 *
 * The wording narrowed from "synthetic data only" when the 28 real campus
 * locations were imported. A banner that overstates is not the safe direction
 * it looks like: this one exists to say precisely which parts of the screen
 * are not real, and a claim the reader can see is false is a claim they stop
 * reading. What is placeholder here is the faculty roster and the schedules.
 */
export default function DemoBanner() {
  const [info, setInfo] = useState(null);
  const [open, setOpen] = useState(false);
  // Matches the navigation above it: edge to edge on application surfaces,
  // centred on the landing page. A banner indented differently from the bar it
  // sits under reads as a rendering fault rather than a notice.
  const appChrome = useLocation().pathname !== '/';

  useEffect(() => {
    api.health()
      .then((h) => { if (h.demoMode) setInfo(h); })
      .catch(() => { /* the affected views report their own connectivity */ });
  }, []);

  if (!info) return null;

  return (
    <div className="shrink-0 border-b border-warning/35 bg-warning-subtle">
      <div className={appChrome ? 'container-app' : 'container-x'}>
        <div className="flex items-center gap-2.5 py-2">
          <FlaskConical className="h-3.5 w-3.5 shrink-0 text-warning" strokeWidth={2} aria-hidden />
          <p className="min-w-0 flex-1 text-label text-warning">
            <span className="font-semibold">Demo mode</span>
            <span className="mx-1.5 opacity-50" aria-hidden>&mdash;</span>
            Synthetic faculty and schedule data. Nothing shown here is a research result.
          </p>
          <button
            type="button"
            onClick={() => setOpen((v) => !v)}
            aria-expanded={open}
            aria-controls="demo-detail"
            className="-my-1 flex min-h-[2.25rem] shrink-0 items-center gap-1 rounded px-1 text-label font-medium text-warning underline decoration-warning/40 underline-offset-2 transition-colors duration-state hover:decoration-warning"
          >
            {open ? 'Less' : 'What this means'}
            <ChevronDown
              className={`h-3 w-3 transition-transform duration-menu ${open ? 'rotate-180' : ''}`}
              aria-hidden
            />
          </button>
        </div>

        {open && (
          <div id="demo-detail" className="border-t border-warning/25 py-3">
            <dl className="grid gap-x-8 gap-y-2 text-label text-warning sm:grid-cols-3">
              {[
                ['Availability', 'A deterministic schedule lookup. No Random Forest has been trained.'],
                ['Replies', 'Composed from templates over retrieved text, not generated by Llama 3.1 8B.'],
                ['Data', 'Placeholder faculty, schedules and documents, marked [DEMO] wherever they appear. Campus locations are real, but traced from satellite imagery rather than surveyed on site.'],
              ].map(([k, v]) => (
                <div key={k}>
                  <dt className="font-semibold">{k}</dt>
                  <dd className="mt-0.5 leading-relaxed opacity-90">{v}</dd>
                </div>
              ))}
            </dl>
            <p className="mt-3 text-label leading-relaxed text-warning opacity-80">
              The evaluation harness refuses to run against synthetic data, so no
              figure produced in this mode can reach the thesis.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
