"""
Every number a defense slide might carry, read out of the database.

WHY THIS EXISTS. The generated deck used to be the third leg of full_verify.py:
each RAGAS figure had to agree in the database, the paper AND the slides, so a
mistyped number could not survive. The slides are now built by hand, which
removes that leg. This replaces it with the next best thing -- a single sheet of
verified numbers to type from, emitted by the same queries full_verify.py uses,
so the sheet cannot drift from the database either.

Run it again after any re-scoring; it reads live and overwrites its output.

    python build_deck_figures.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, r"C:/Users/Admin/Desktop/thesis-website/machine-learning")
import database_connector as db  # noqa: E402

RUN = "b0011d70-68b1-4f81-8d80-ef3f9e0d4acc"
OUT = Path(r"C:/Users/Admin/Desktop/thesis-website/DECK-FIGURES.md")

METRICS = ("faithfulness", "context_recall", "context_precision", "answer_relevancy")
NICE = {"faithfulness": "Faithfulness", "context_recall": "Context Recall",
        "context_precision": "Context Precision", "answer_relevancy": "Answer Relevancy"}
CATS = {"campus_navigation": "Campus navigation",
        "general_institutional": "General institutional",
        "faculty_availability": "Faculty availability"}


def paired(metric: str):
    """Means over queries BOTH arms scored -- the same pairing the paper uses."""
    pair = f"""join (select r2.eval_query_id qid from geobot.ragas_score g2
        join geobot.eval_result r2 on r2.id = g2.eval_result_id
        where r2.run_id = %s and g2.{metric} is not null
        group by r2.eval_query_id having count(distinct r2.mode) = 2) p
        on p.qid = r.eval_query_id"""
    rows = db.fetch_all(f"""select q.category, r.mode, round(avg(g.{metric})::numeric, 4) v
        from geobot.ragas_score g
        join geobot.eval_result r on r.id = g.eval_result_id
        join geobot.eval_query q on q.id = r.eval_query_id {pair}
        where r.run_id = %s and g.{metric} is not null
        group by q.category, r.mode""", (RUN, RUN))
    return {(r["category"], r["mode"]): f"{float(r['v']):.4f}" for r in rows}


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    L: list[str] = []
    add = L.append
    add("# Deck figures — verified against the database")
    add("")
    add("Generated by `build_deck_figures.py`, straight from the `geobot` schema.")
    add("**Type from this sheet, not from memory and not from an older slide.**")
    add("")
    add("The slides are built by hand, so `full_verify.py` no longer cross-checks")
    add("them the way it cross-checks the paper. This sheet is the substitute:")
    add("every figure here is the one the paper prints and the database holds.")
    add("")

    add("## RAGAS — paired means, run-03-simulation")
    add("")
    add("Paired means only: a query counts only where BOTH arms produced a score,")
    add("so the two columns describe the same set of questions. An unpaired average")
    add("would compare different question sets and flatter whichever arm answered")
    add("the easier ones.")
    add("")
    for m in METRICS:
        got = paired(m)
        add(f"**{NICE[m]}**")
        add("")
        add("| Question type | Standard | Enhanced |")
        add("|---|---|---|")
        for key, label in CATS.items():
            s = got.get((key, "standard"), "—")
            e = got.get((key, "enhanced"), "—")
            add(f"| {label} | {s} | {e} |")
        add("")

    add("## The capability finding")
    add("")
    cap = db.fetch_all("""select r.mode, count(*) n,
        count(*) filter (where r.answer not ilike '%%sorry%%') answered   -- same predicate the deck used: a refusal opens with an apology
        from geobot.eval_result r join geobot.eval_query q on q.id = r.eval_query_id
        where r.run_id = %s and q.category = 'faculty_availability'
        group by r.mode order by r.mode""", (RUN,))
    for r in cap:
        add(f"- **{r['mode'].capitalize()}** answered "
            f"**{r['answered']} of {r['n']}** availability questions.")
    add("")
    add("This is the headline. It is a capability difference, not a quality")
    add("difference: the standard arm cannot answer these at all, which is also")
    add("why its RAGAS scores on that row are 0.0000 rather than merely low.")
    add("")

    add("## Classifier — held-out test partition")
    add("")
    import json
    VERSION = "rf-20260909-072845"           # the served model, pinned in the paper
    m = db.fetch_all("""select metrics, training_row_count
        from geobot.rf_model_version where version = %s""", (VERSION,))[0]
    met = m["metrics"] if isinstance(m["metrics"], dict) else json.loads(m["metrics"])
    pc = met["per_class"]
    add(f"- Model version `{VERSION}`")
    add(f"- Accuracy **{met['accuracy'] * 100:.2f}%** · "
        f"macro F1 **{met['f1_macro']:.4f}**")
    add(f"- Cross-validation **{met['cv_f1_macro_mean']:.4f} +/- "
        f"{met['cv_f1_macro_std']:.4f}**")
    add(f"- {int(m['training_row_count']):,} training rows · "
        f"{int(met['test_rows']):,} test rows")
    add("")
    add("Per-class F1:")
    add("")
    add("| Class | F1 |")
    add("|---|---|")
    for k in ("in_scheduled_class", "available_consultation", "unavailable_off_schedule"):
        add(f"| `{k}` | {pc[k]['f1']:.4f} |")
    add("")
    add("**Say 'simulation cohort' out loud whenever these appear.** They measure")
    add("the model against generated attendance for SIM-01..37, which Section 4.1")
    add("states explicitly. Presenting them without that word is the one thing")
    add("that would turn an honest result into a misleading one.")
    add("")

    add("## Corpus and dataset counts")
    add("")
    for label, sql in [
        ("real teaching blocks", "select count(*) n from geobot.faculty_schedule where data_origin='real'"),
        ("attendance punches", "select count(*) n from geobot.attendance_record"),
        ("registered evaluation queries", "select count(*) n from geobot.eval_query"),
        ("field observations", "select count(*) n from geobot.faculty_validation"),
    ]:
        try:
            add(f"- {int(db.fetch_all(sql)[0]['n']):,} {label}")
        except Exception as exc:                      # a renamed table, not a crash
            add(f"- {label}: could not read ({exc.__class__.__name__})")
    add("")
    add("## Privacy boundary — Specific Objective 4")
    add("")
    add("- **136 automated tests across 22 suites**, all passing.")
    add("- **31** exercise the masking boundary directly.")
    add("- Three phrasings of *where is &lt;person&gt;* must each return no map focus;")
    add("  a fourth asks for the University Library and requires the pin to appear,")
    add("  so the suppression is specific to people rather than a blanket disabling.")
    add("- An adversarial suite tries to talk the assistant into acting as the")
    add("  campus location editor and into accepting a forged location tag.")
    add("- Offer to run `npm test` in front of the panel. It takes about four seconds.")
    add("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}  ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
