/**
 * HTTP surface.
 *
 * Boundary rules enforced here (audit Section F):
 *   1. Groq is called only from the server. The key never leaves it.
 *   2. Flask is never exposed publicly.
 *   3. The frontend never holds the Supabase service_role key.
 *   4. /api/chat CANNOT select the standard arm.
 *   5. Every response body is an explicit allowlist.
 */

import crypto from 'node:crypto';
import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';

import { db, ml, log } from '../utilities/service-clients.js';
import { config } from '../utilities/configuration.js';
import { optionalAuth, requireAuth, requireRole } from '../middleware/authentication.js';
import { assertNoLeak, toChatDto } from '../middleware/privacy-masking-middleware.js';
import { logChat, runPipeline } from '../services/knowledge-search-service.js';
import { resolvePresence } from '../services/faculty-presence-service.js';
import { admin } from './admin-routes.js';

export const api = Router();

const limit = (max) =>
  rateLimit({
    windowMs: config.rateLimit.windowMs,
    max,
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: 'rate limit exceeded, please slow down' },
  });

// Audit F-29: session identity is a SALTED HASH, never a raw IP. The chat log
// exists to detect abuse, not to build a record of who asked what.
function sessionHash(req) {
  return crypto
    .createHash('sha256')
    .update(`${req.ip}:${req.headers['user-agent'] ?? ''}:${config.sessionSalt}`)
    .digest('hex')
    .slice(0, 32);
}

// ---------------------------------------------------------------------------
// Public
// ---------------------------------------------------------------------------

api.get('/health', async (_req, res) => {
  let mlOk = false;
  let rfReady = false;
  try {
    const h = await ml.health();
    mlOk = h.status === 'ok';
    rfReady = Boolean(h.rf_ready);
  } catch { /* ML down is a degraded state, not a crash */ }
  res.json({
    status: 'ok',
    ml: mlOk,
    randomForestTrained: rfReady,
    // Surfaced so the UI can show a persistent banner. Audit R5/R6/R8: a demo
    // screenshot must never be mistakable for a result.
    demoMode: config.demoMode,
    demoNotice: config.demoMode
      ? 'Demonstration mode. Availability comes from a deterministic schedule '
        + 'lookup, not a trained Random Forest. Answers are composed from '
        + 'templates over retrieved text, not generated by Llama 3.1 8B. '
        // Campus locations stopped being placeholders when the real 28 were
        // imported, and saying otherwise would understate the data in a
        // document about data provenance. Their limitation is different and
        // more specific: traced from imagery, not surveyed on site.
        + 'Faculty data are placeholders. Campus locations are real but their '
        + 'coordinates were traced from satellite imagery, not surveyed on '
        + 'site as thesis §3.4.1(a) requires.'
      : null,
  });
});

const historySchema = z.array(z.object({
  role: z.enum(['user', 'assistant']),
  content: z.string().max(600),
})).max(12).optional();

const chatSchema = z.object({
  query: z.string().min(2).max(500),
  // Capped at the edge as well as sanitised in the pipeline: the schema stops
  // a client posting a megabyte of "history" into a prompt, and
  // sanitiseHistory decides what of it may actually be replayed.
  history: historySchema,
  // NOTE the absence of `mode`. Audit F-16: the standard/enhanced switch is an
  // evaluation concern. Exposed publicly it would let anyone drive the
  // baseline arm and would make evaluation runs indistinguishable from live
  // traffic in the logs. This endpoint is hard-wired to `enhanced`.
});

api.post('/chat', optionalAuth, limit(config.rateLimit.chatMax), async (req, res, next) => {
  try {
    const { query, history } = chatSchema.parse(req.body);

    // Audit F-29. Availability requires a campus account; the map and
    // institutional Q&A stay open. Masking protects the granularity of one
    // answer but does nothing about volume, so an anonymous availability
    // endpoint can be polled into a presence timeline. Attaching a person to
    // the query makes that attributable and rate-limitable.
    const signedIn = Boolean(req.user);

    // Present-moment only, for everyone. No historical lookups ("was she in
    // yesterday") and no forecasting ("when will she be free") — either turns
    // a generalized status into a movement profile.
    const result = await runPipeline({
      query,
      mode: 'enhanced',
      at: new Date(),
      allowAvailability: signedIn,
      history,
    });
    result.route.query = query;

    await logChat(result, { sessionHash: sessionHash(req) });
    const dto = assertNoLeak(toChatDto(result));
    dto.authRequired = result.availabilityWithheld ?? false;
    res.json(dto);
  } catch (err) {
    next(err);
  }
});

/**
 * Landing-page comparison widget (audit open decision 3).
 *
 * Runs both arms so visitors can see what Context Fusion actually adds — the
 * best demonstration of the study's contribution available. It preserves the
 * F-16 invariant by accepting ONLY curated queries: `mode` is still not a
 * client-controlled parameter on free text, and a fixed query list cannot be
 * polled to reconstruct anyone's presence timeline (F-29).
 */
api.get('/demo/queries', limit(config.rateLimit.generalMax), async (_req, res, next) => {
  try {
    const { data, error } = await db
      .from('demo_query')
      .select('id, label, query_text, category')
      .eq('is_active', true)
      .order('sort_order');
    if (error) throw error;
    res.json({ queries: data ?? [] });
  } catch (err) { next(err); }
});

api.post('/demo/compare', limit(config.rateLimit.demoMax), async (req, res, next) => {
  try {
    // Not .uuid(): the value is looked up against the demo_query allowlist
    // below, so the table is the authority on what is acceptable, not the
    // id format. Demo-mode fixtures use short ids.
    const { demoQueryId } = z.object({ demoQueryId: z.string().min(1).max(64) }).parse(req.body);

    const { data: demo, error } = await db
      .from('demo_query')
      .select('query_text, category')
      .eq('id', demoQueryId)
      .eq('is_active', true)
      .maybeSingle();
    if (error) throw error;
    if (!demo) return res.status(404).json({ error: 'unknown demo query' });

    // allowAvailability is on here despite being a public endpoint: the query
    // list is curated and fixed (audit F-16), so it cannot be repurposed to
    // poll an arbitrary person's status.
    const [standard, enhanced] = await Promise.all([
      runPipeline({ query: demo.query_text, mode: 'standard', allowAvailability: true }),
      runPipeline({ query: demo.query_text, mode: 'enhanced', allowAvailability: true }),
    ]);

    for (const r of [standard, enhanced]) {
      r.route.query = demo.query_text;
      await logChat(r, { sessionHash: sessionHash(req), isDemo: true });
    }

    res.json({
      query: demo.query_text,
      category: demo.category,
      standard: assertNoLeak(toChatDto(standard)),
      enhanced: assertNoLeak(toChatDto(enhanced)),
      // Context Fusion breakdown — what the enhanced arm added, structurally.
      fusion: {
        retrievedChunks: enhanced.sources.length,
        statusInjected: Boolean(enhanced.masked),
        statusLabel: enhanced.statusLabel,
        contextItems: enhanced.contextsForRagas.length,
      },
      // Audit R8: a single demo timing is NOT a research measurement. Response
      // Time figures come from evalRunner, interleaved, median and p95.
      timingNote: 'Illustrative only — not a research measurement.',
    });
  } catch (err) { next(err); }
});

api.get('/map/pois', limit(config.rateLimit.generalMax), async (req, res, next) => {
  try {
    const { data, error } = await db
      .from('poi')
      .select('id, slug, name, poi_type, lat, lng, building_function, description, is_featured, icon, data_origin, department:department_id (name)')
      .order('name');
    if (error) throw error;
    res.json({
      pois: (data ?? []).map((p) => ({
        id: p.id,
        slug: p.slug ?? null,
        icon: p.icon ?? null,
        // Audit F-38 / R1: synthetic rows are visibly marked wherever they
        // surface, so a screenshot of placeholder data is self-evidently
        // placeholder data.
        name: p.data_origin === 'synthetic' ? `[DEMO] ${p.name}` : p.name,
        type: p.poi_type,
        lat: p.lat,
        lng: p.lng,
        buildingFunction: p.building_function,
        description: p.description,
        department: p.department?.name ?? null,
        isFeatured: p.is_featured,
        isSynthetic: p.data_origin === 'synthetic',
      })),
    });
  } catch (err) { next(err); }
});

api.get('/faculty/search', limit(config.rateLimit.generalMax), async (req, res, next) => {
  try {
    const q = String(req.query.q ?? '').trim();
    if (q.length < 2) return res.json({ candidates: [] });

    const { data, error } = await db.rpc('resolve_faculty_candidates', {
      p_needle: q,
      p_limit: 5,
    });
    if (error) throw error;
    res.json({
      // Audit F-31: returns ALL candidates. The caller asks when there is more
      // than one; it never auto-selects a winner.
      candidates: (data ?? []).map((c) => ({
        id: c.faculty_id,
        name: c.full_name,
        department: c.department_name,
        matchKind: c.match_kind,
      })),
    });
  } catch (err) { next(err); }
});

// ---------------------------------------------------------------------------
// Guard portal
// ---------------------------------------------------------------------------

api.get('/guard/roster', requireAuth, requireRole('guard', 'researcher'),
  async (_req, res, next) => {
    try {
      const { data, error } = await db.rpc('resolve_presence_roster', {
        p_at: new Date().toISOString(),
        p_timezone: config.presence.timezone,
      });
      if (error) throw error;
      res.json({
        roster: (data ?? []).map((r) => ({
          facultyId: r.faculty_id,
          name: r.full_name,
          department: r.department_name,
          // Tri-state, surfaced honestly. "unknown" is displayed as unknown,
          // never rendered as "off campus" (audit F-07).
          presenceState: r.presence_state,
          lastEventType: r.last_event_type,
          lastEventAt: r.last_event_at,
        })),
      });
    } catch (err) { next(err); }
  });

const eventSchema = z.object({
  // Not .uuid(): the real authorization check is the consented-roster lookup
  // below (audit W3), not the identifier format. Demo fixtures use short ids.
  facultyId: z.string().min(1).max(64),
  eventType: z.enum(['arrival', 'departure']),
  note: z.string().max(280).optional(),
  supersedesId: z.string().min(1).max(64).optional(),
});

api.post('/guard/events', requireAuth, requireRole('guard'),
  async (req, res, next) => {
    try {
      const body = eventSchema.parse(req.body);

      const { data: guard } = await db
        .from('guard_user')
        .select('id')
        .eq('auth_user_id', req.user.id)
        .eq('is_active', true)
        .maybeSingle();
      if (!guard) return res.status(403).json({ error: 'no active guard record' });

      // Audit W3 (IDOR): consented roster only.
      const { data: faculty } = await db
        .from('faculty')
        .select('id')
        .eq('id', body.facultyId)
        .eq('is_consented', true)
        .eq('is_active', true)
        .maybeSingle();
      if (!faculty) {
        return res.status(403).json({ error: 'faculty is not on the consented roster' });
      }

      const { data, error } = await db
        .from('guard_presence_event')
        .insert({
          faculty_id: body.facultyId,
          event_type: body.eventType,
          logged_by: guard.id,
          note: body.note ?? null,
          supersedes_id: body.supersedesId ?? null,
          data_origin: 'real',
        })
        .select('id, occurred_at')
        .single();
      if (error) throw error;

      const presence = await resolvePresence(body.facultyId);
      res.status(201).json({ event: data, presenceState: presence.state });
    } catch (err) { next(err); }
  });

// ---------------------------------------------------------------------------
// Faculty validation portal (thesis §3.8.2)
// ---------------------------------------------------------------------------

api.get('/validate/context', requireAuth, requireRole('validator'),
  async (req, res, next) => {
    try {
      // In-system capture (audit C14): the system records its OWN prediction,
      // so a validator cannot misremember what it said. That removes a
      // transcription-error attack on the results.
      const { data: faculty } = await db
        .from('faculty')
        .select('id, full_name')
        .eq('id', req.user.facultyId)
        .maybeSingle();

      const result = await runPipeline({
        query: `Is ${faculty?.full_name} available right now?`,
        mode: 'enhanced',
        allowAvailability: true,
      });

      const { data: statuses } = await db
        .from('availability_status')
        .select('code, display_label')
        .order('sort_order');

      res.json({
        faculty: { id: faculty?.id, name: faculty?.full_name },
        systemStatus: result.masked?.statusCode ?? null,
        systemStatusLabel: result.statusLabel,
        overrideApplied: result.overrideApplied,
        estimatedAt: result.masked?.maskedAt ?? null,
        statusOptions: statuses ?? [],
      });
    } catch (err) { next(err); }
  });

const validationSchema = z.object({
  systemStatus: z.enum(['available_consultation', 'in_scheduled_class', 'unavailable_off_schedule']),
  actualStatus: z.enum(['available_consultation', 'in_scheduled_class', 'unavailable_off_schedule']),
  correctness: z.enum(['correct', 'partially_correct', 'incorrect']),
  overrideApplied: z.boolean().optional(),
  notes: z.string().max(500).optional(),
});

api.post('/validate/entries', requireAuth, requireRole('validator'),
  async (req, res, next) => {
    try {
      const body = validationSchema.parse(req.body);
      const { data, error } = await db
        .from('faculty_validation')
        .insert({
          faculty_id: req.user.facultyId,
          system_status: body.systemStatus,
          actual_status: body.actualStatus,
          correctness: body.correctness,
          override_applied: body.overrideApplied ?? false,
          notes: body.notes ?? null,
          data_origin: 'real',
        })
        .select('id, queried_at')
        .single();
      if (error) throw error;
      res.status(201).json({ entry: data });
    } catch (err) { next(err); }
  });

api.get('/validate/entries', requireAuth, requireRole('validator'),
  async (req, res, next) => {
    try {
      const { data, error } = await db
        .from('faculty_validation')
        .select('id, queried_at, system_status, actual_status, correctness, include_in_matrix')
        .eq('faculty_id', req.user.facultyId)
        .order('queried_at', { ascending: false })
        .limit(100);
      if (error) throw error;
      res.json({ entries: data ?? [] });
    } catch (err) { next(err); }
  });

// ---------------------------------------------------------------------------
// Research
// ---------------------------------------------------------------------------

/**
 * Evaluation status for the UI.
 *
 * Audit R6/R7/R8 and brief §2.7: metric cards render an EMPTY STATE until a
 * real run exists. There is no placeholder number anywhere in this response,
 * because a placeholder number is one screenshot away from becoming evidence.
 */
api.get('/eval/status', async (_req, res, next) => {
  try {
    if (config.demoMode) {
      // Audit R7/R8. There is nothing to report and there never will be from
      // demo mode. Saying so explicitly beats returning an empty list that
      // could read as "evaluated, scored zero".
      return res.json({
        hasResults: false,
        runs: [],
        scoredResults: 0,
        activeModel: null,
        demoMode: true,
        disclaimer:
          'Demonstration mode. No evaluation can be run against placeholder '
          + 'data: the harness refuses synthetic rows by design. RAGAS scores, '
          + 'classification accuracy and faculty validation results will appear '
          + 'only after real evaluation runs against real institutional data.',
      });
    }
    const { data: runs } = await db
      .from('eval_run')
      .select('id, run_label, started_at, finished_at, groq_model_id, judge_model, top_k')
      .order('started_at', { ascending: false })
      .limit(5);

    const { count: scored } = await db
      .from('ragas_score')
      .select('id', { count: 'exact', head: true });

    const { data: models } = await db
      .from('rf_model_version')
      .select('version, trained_at, label_source, split_strategy')
      .order('trained_at', { ascending: false })
      .limit(1);

    res.json({
      hasResults: Boolean(scored),
      runs: runs ?? [],
      scoredResults: scored ?? 0,
      activeModel: models?.[0] ?? null,
      disclaimer:
        'ISU-GeoBot is a research prototype. No evaluation results have been ' +
        'published for this deployment. RAGAS scores, classification accuracy ' +
        'and faculty validation figures will appear here only after real ' +
        'evaluation runs have been completed and recorded.',
    });
  } catch (err) { next(err); }
});

api.use('/admin', admin);

/**
 * Who am I and what may I do. The frontend renders navigation from this rather
 * than inferring permissions client-side, so a role check is never a UI-only
 * decision.
 */
api.get('/me', requireAuth, (req, res) => {
  res.json({
    id: req.user.id,
    email: req.user.email,
    roles: req.user.roles,
    facultyId: req.user.facultyId,
    can: {
      askAvailability: true,
      manageLocations: req.user.roles.some((r) => ['admin', 'researcher'].includes(r)),
      logPresence: req.user.roles.includes('guard'),
      validate: req.user.roles.includes('validator'),
      controlOwnVisibility: req.user.roles.some((r) => ['faculty', 'validator'].includes(r)),
      runEvaluation: req.user.roles.includes('researcher'),
    },
  });
});

api.use((err, _req, res, _next) => {
  if (err?.name === 'ZodError') {
    return res.status(400).json({ error: 'invalid request', detail: err.errors });
  }
  if (err?.name === 'MaskingViolation') {
    // Audit F-26. Never degrade into a default status: a boundary violation is
    // a bug, and answering anyway would defeat the boundary.
    log.error({ err: err.message, detail: err.detail }, 'status masking violation');
    return res.status(500).json({ error: 'availability could not be resolved safely' });
  }
  log.error({ err: err.message, stack: err.stack }, 'request failed');
  res.status(err.status ?? 500).json({
    error: err.status === 503 ? 'service_unavailable' : 'internal_error',
    message: err.status && err.status < 500 ? err.message : 'Something went wrong.',
  });
});
