/**
 * DEMO_MODE adapters.
 *
 * Replaces the three external dependencies — Supabase, the Flask ML service,
 * and Groq — with local implementations so the full application runs with no
 * credentials and no Python.
 *
 * WHAT IS REAL IN DEMO MODE
 *   · the query router and its gazetteer
 *   · the tri-state presence resolution and deterministic override
 *   · the ENTIRE status masking boundary, including the egress filter
 *   · the Context Fusion prompt construction
 *   · retrieval by exact cosine over embedded chunks
 *   · both pipeline arms and the single-branch mode flag
 *
 * WHAT IS FAKE IN DEMO MODE — and must never be reported
 *   · the classifier. It is a schedule lookup, NOT a Random Forest. There is
 *     no trained model, so there is nothing to serve (audit R6).
 *   · the language model. Answers are composed from templates over the
 *     retrieved context, NOT generated by Llama 3.1 8B (audit R5/R8).
 *   · the embeddings. Hashed lexical overlap, NOT all-MiniLM-L6-v2.
 *
 * Every response in demo mode carries `demoMode: true`, /api/health reports it,
 * the UI shows a persistent banner, and /api/eval/* refuses to run. The point
 * is that nobody — including a tired researcher at 2am — can mistake a demo
 * screenshot for a result.
 */

import * as D from './mock-campus-data.js';
import { demoDb } from './mock-database.js';
import { embed } from './mock-text-embeddings.js';

export { demoDb };

/**
 * Stand-in for the Flask service.
 *
 * /predict deliberately reports source: 'schedule_lookup'. It is NOT dressed up
 * as a model prediction: the probability vector is one-hot, which is what a
 * deterministic rule produces, and any UI or log reading it can tell the
 * difference.
 */
export const demoMl = {
  async embed(text) {
    return { embedding: embed(text), dim: 384, model: 'demo-lexical-hash (NOT all-MiniLM-L6-v2)' };
  },

  async predict(context) {
    const faculty = D.faculty.find(
      (f) => D.facultyPseudonymMap.find((m) => m.pseudonym_id === context.pseudonym_id)?.faculty_id === f.id,
    );
    const { data } = await demoDb.rpc('schedule_lookup_status', {
      p_faculty_id: faculty?.id,
      p_at: context.when,
    });
    const status = data[0].status_code;

    return {
      predicted_class: status,
      // One-hot, because a rule is not probabilistic. A real forest returns a
      // distribution; this deliberately does not pretend to.
      probabilities: Object.fromEntries(
        D.availabilityStatus.map((s) => [s.code, s.code === status ? 1 : 0]),
      ),
      model_version: 'DEMO-schedule-lookup',
      label_source: 'schedule_derived',
      source: 'schedule_lookup',
      internal_only: true,
    };
  },

  async modelInfo() {
    return {
      rf_ready: false,
      demo: true,
      message:
        'Demo mode: availability comes from a deterministic schedule lookup. ' +
        'No Random Forest has been trained.',
    };
  },

  async health() {
    return { status: 'ok', demo: true, embedder: 'demo-lexical-hash', rf_ready: false };
  },
};

/**
 * Stand-in for Groq.
 *
 * Composes an answer from the retrieved context using templates. It is
 * extractive by construction, which has one useful property: it CANNOT
 * hallucinate a room number, so the egress filter has nothing to catch in demo
 * mode. That is a property of the stub, not evidence the filter works — the
 * evidence for that is `npm test`.
 */
export async function demoGenerate(messages) {
  const prompt = messages.at(-1)?.content ?? '';
  // Everything between the system prompt and the fused turn is conversation
  // history. A real model would simply attend to it; the stub has to be told.
  const history = messages.slice(1, -1);

  const rawQuery = (prompt.match(/USER QUERY:\n([\s\S]*)$/) ?? [])[1]?.trim() ?? '';
  const { query, resolved } = resolveDeixis(rawQuery, history);
  const availability = (prompt.match(/AVAILABILITY \([^)]*\):\n([\s\S]*?)\n\n/) ?? [])[1] ?? null;
  const contextBlock = (prompt.match(/RETRIEVED CONTEXT[^:]*:\n([\s\S]*?)(?:\n\nAVAILABILITY|\n\nUSER QUERY)/) ?? [])[1] ?? '';

  const passages = contextBlock
    .split(/\n\n---\n\n/)
    .map((b) => b.replace(/^\[\d+\][^\n]*\n/, '').trim())
    // The prompt's own "(no relevant institutional documents were retrieved)"
    // placeholder is not a passage. Without this it gets spliced into the
    // answer as though it were retrieved text.
    .filter((b) => b && !b.startsWith('(no relevant'));

  // Simulated inference latency, so the typing indicator is visible and the
  // demo feels like the real thing.
  await new Promise((r) => setTimeout(r, 280 + Math.random() * 320));

  const noContext = passages.length === 0;

  if (availability) {
    const name = (availability.match(/Faculty member: (.+)/) ?? [])[1] ?? 'The faculty member';
    const status = (availability.match(/Estimated status: (.+)/) ?? [])[1] ?? 'Unavailable';
    // Deliberately does NOT splice in the top retrieved chunk. The lexical
    // embedder ranks weakly on availability phrasing, so the best chunk is
    // often unrelated, and tacking it on would make the answer look like the
    // real pipeline hallucinating rather than the stub being a stub.
    return (
      `Based on the current schedule, ${name} is estimated to be: ${status}. ` +
      'This is a schedule-derived estimate rather than a confirmed observation, ' +
      'so it is worth coordinating with the department office before visiting.'
    );
  }

  // "How do I get to the library" is a navigation question and was not being
  // treated as one, because the old list only recognised the word "where".
  // Route-shaped phrasings are how people ask once they already know the name.
  const navigational = /\b(where|location|locate|find|show|get to|getting to|way to|route|directions?|take me|walk to|how do i get|nasaan|saan|papunta)\b/i
    .test(query);
  // When a pronoun was resolved from history, THAT is the place being asked
  // about. "How do I get there from the Oval" names two locations and means the
  // first one; scoring the whole sentence would pick the Oval, which is where
  // the user already is.
  const tag = navigational ? locationTag(prompt, resolved ?? query) : '';

  if (noContext) {
    // Naming a place and describing it are different capabilities. The lexical
    // stub retrieves weakly, so it often has nothing to say about a building it
    // can nonetheless identify — and pointing at it on the map is still the
    // right answer to "where is it". The real pipeline reaches this branch far
    // less often; the branch exists so the demo does not look broken when it
    // does.
    if (tag) {
      return (
        'I can show you where that is on the campus map. I do not have a '
        + 'document describing it in more detail yet.' + tag
      );
    }
    return (
      'I do not have information about that in the documents available to me. ' +
      'Try asking about a campus building, an administrative office, or an ' +
      'institutional policy covered by the university documents.'
    );
  }

  return `${firstSentences(passages[0], 3)}${
    passages[1] ? ` ${firstSentences(passages[1], 1)}` : ''
  }${
    navigational ? ' You can see the exact position highlighted on the campus map.' : ''
  }${tag}`;
}

/**
 * The stub's stand-in for a model resolving "there".
 *
 * "How do I get there from the Oval?" carries no noun. A language model handles
 * this by attending to the previous turns; a template engine cannot, so the
 * stub does the one thing that makes the demo honest: it rewrites the deictic
 * word with whatever place the last assistant turn actually named, then answers
 * that question normally.
 *
 * It is a stand-in, not an implementation of coreference. It resolves one word
 * against one prior turn, and it is only ever reached in DEMO_MODE — with a
 * Groq key the real model sees the same history and does this properly.
 */
const DEIXIS = /\b(there|it|that place|the same place)\b/i;

function resolveDeixis(query, history) {
  if (!DEIXIS.test(query)) return { query, resolved: null };

  // The most recent assistant turn that named a campus place. Titles are the
  // capitalised runs the place-cards are written with.
  for (let i = history.length - 1; i >= 0; i -= 1) {
    if (history[i].role !== 'assistant') continue;
    const named = String(history[i].content ?? '')
      .match(/\b((?:[A-Z][A-Za-z'’-]+\s+){1,4}(?:Building|Center|Centre|Library|Hall|Office|Park|Plaza|Gate|Oval|Gymnasium|School|College|Station|Dormitory|Canteen|Infirmary|Amphitheater))\b/);
    if (named) return { query: query.replace(DEIXIS, named[1]), resolved: named[1] };
  }
  return { query, resolved: null };
}

/**
 * The stub's stand-in for the real model choosing a [LOCATION: id].
 *
 * Lexical, like the rest of demo mode: it reads the CAMPUS LOCATIONS block out
 * of the prompt it was given and matches the query against the names in it. It
 * cannot emit an id that was not in the prompt — but the server validates the
 * id regardless, because in production the thing choosing it is a language
 * model and no prompt instruction is a guarantee.
 *
 * A name matches on either of two grounds, because campus names come in two
 * shapes:
 *
 *   · most of the name is in the query — "the university library" against
 *     "University Library"
 *   · the query contains a word no other location uses — "the oval" against
 *     "The Oval (Athletic Field)", where two thirds of the name is decoration
 *     nobody says out loud
 *
 * Neither test alone is enough. Coverage alone loses every parenthesised name;
 * rarity alone matches on any distinctive word that happens to appear. Ties go
 * to the rarer words, so "library" picks the library over Library Park.
 */
function locationTag(prompt, query) {
  // Matched to end of line rather than to the first colon: the header itself
  // contains one, inside the "[LOCATION: id]" it is explaining.
  const block = (prompt.match(/CAMPUS LOCATIONS[^\n]*\n([\s\S]*?)(?:\n\n|$)/) ?? [])[1];
  if (!block) return '';

  const entries = [];
  for (const line of block.split('\n')) {
    const m = line.match(/^- ([a-z0-9-]+) [—-] (.+)$/);
    if (m) entries.push({ slug: m[1], words: m[2].toLowerCase().match(/[a-z]{4,}/g) ?? [] });
  }

  const frequency = new Map();
  for (const e of entries) {
    for (const w of new Set(e.words)) frequency.set(w, (frequency.get(w) ?? 0) + 1);
  }

  const q = query.toLowerCase();
  let best = null;
  for (const e of entries) {
    const words = [...new Set(e.words)];
    const matched = words.filter((w) => q.includes(w));
    if (!matched.length) continue;

    const coverage = matched.length / words.length;
    const distinctive = matched.some((w) => frequency.get(w) === 1);
    if (coverage < 0.5 && !distinctive) continue;

    const score = matched.reduce((sum, w) => sum + 1 / frequency.get(w), 0);
    if (!best || score > best.score) best = { slug: e.slug, score };
  }
  return best ? ` [LOCATION: ${best.slug}]` : '';
}

function firstSentences(text, n) {
  return text.split(/(?<=[.!?])\s+/).slice(0, n).join(' ').trim();
}
